<html>
  <head>
    <title>Coffee Time!</title>
    <link rel="stylesheet" type="text/css" href="./style/milkyStyle.css">
    <link rel="shortcut icon" href="./style/imgs/icon.ico">
    <!-- Testing 
    <link rel="stylesheet" type="text/css" href="../milkyStyle.css">
    <link rel="shortcut icon" href="../imgs/icon.ico"> -->
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/coffee2.0"><p>Coffee Project</p></a>
        </div>
        <div class="align-nav-buttons">
          <button type="button" id="usercontrol" class="btn btn-default navbar-btn" data-toggle="modal" data-target="#modal-usercontrol">Usercontrol</button>
          <button type="button" class="btn btn-default navbar-btn" data-toggle="modal" data-target="#modal-about">About</button>
          <button onclick="window.location.href='/coffee2.0/logout.php'" type="button" class="btn btn-default navbar-btn">Logout</button>
        </div>
      </div>
    </nav>
    
    <!-- Profile box -->
    <div class="container extmarg">
      <div class="positioning-profile-box panel panel-info">
        <div class="panel-heading bigger">profile</label></div>
          <div class="panel-body">
            <div class="ProfileImage">
              <input type="file" id="upload" name="upload" style="visibility: hidden; width: 1px; height: 1px" />
              <a onclick="document.getElementById('upload').click(); return false;">
                <img onclick="" id="file_upload" src="[/user_profile_pic\]" alt="profile-picture"> 
                <span>change Profile Picture</span>
              </a> 
            </div>
                    <label>name:&nbsp;</label>[/user_name\]</p>
                    <label>Total consumed cups of coffee:&nbsp;</label> [/cups_consumed\]</p>
                    <label>Money:&nbsp;</label><span class="glyphicon glyphicon-euro">[/coins\]</span></p>
          </div>
      </div>


    <!-- coffee_session box -->
    <div class="sessionpanel">
        <div class="positioning-profile-box panel panel-warning">
          <div class="panel-heading bigger">Coffee Sessions</label></div>
            <div class="panel-body" id="cSessionContent">
            <label>existing sessions</label>
              <div class="input-group sessionlist">
                <select id="sessionList" class="form-control">
                  <option value=""></option>
                  
                </select><button>
                <span class="input-group-addon" id="join">Join</span>
                </button>
              </div>
        </div><div class="line"></div>
        <div class="panel-body">
        <label>make new session</label>
          <input id="nameSession" type="text" class="form-control" name="" value="" placeholder="name new coffee session">
          <input id="maxJoinable" type="number" class="form-control" min="1" max="10" maxlength="10" placeholder="Maximal joinable users">
          <button class="btn-primary btnalign" id="createCoffeeSession">create</button>
        </div>
      </div>
    </div>
  
    
    <!-- Jar box -->
    <div class="jarbox">
      <div class="positioning-profile-box panel panel-default">
        <div class="panel-heading bigger">Jar</label></div>
          <div class="panel-body">
            <label>Total amount of money in the jar <span class="glyphicon glyphicon-piggy-bank"></span></label>
            
              <h1><span class="glyphicon glyphicon-euro">[/tcoins\]</span></h1>
              <div class="line"></div>
               <div class="panel-body">
                <label>Declare Expense</label>
                    <div class="form-group">
                       <label class="col-lg-3 mrgTop">Description</label>
                        <div class="col-lg-8">
                          <input type="text" name="desc" id="discrp" title="description" class="form-control" required>
                        </div>
                      </div>
                      <p>&nbsp;</p>
                    <div class="form-group">
                      <label class="col-lg-3 mrgTop">Expense</label>
                      <div class="col-lg-8">
                      <input name="expense" title="expense" id="expense" type="text" class="form-control" required>
                    </div>
                  </div>
                  <input type="button" class="btn-primary btnalign2" id="addexpense" name="addexpense" value="add expense" title="addexpense">
          </div>
        </div>
      </div>
    </div>
  </div>



<!-- usercontrol-model -->
        <div class="modal fade" id="modal-usercontrol" role="dialog">
          <div class="modal-dialog">
          
            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">User control</h4>
              </div>
              <div class="modal-body">
                <h5 class="ital bold">Creat new user</h5><br>
                  <form method="post" role="form">
                    <div class="form-group">
                      <label for="username">New Username:</label>
                      <input type="text" name="user_name" title="user_name" class="form-control" required>
                    </div>
                    <div class="form-group">
                      <label for="pwd">Money:</label>
                      <input name="money" title="money" type="text" class="form-control" id="" required>
                    </div>
                     <div class="form-group">
                     <label for="expiration date">expiration date:</label>
                      <input type="datetime-local" name="expr_date" title="expr_date" required> 
                    </div>
                    <input type="submit" class="btn btn-default" name="createNewUser" title="createNewUser">
                  </form>
                  <br>
                <h5 class="ital bold">Users</h5>
                <div class="panel panel-default">
                  <!-- Default panel contents -->
                  <table class="table table-bordered">
                       <thead>
                        <tr>
                          <th>id</th>
                          <th>username</th>
                          <th>coins</th>
                          <th>options</th>
                        </tr>
                      </thead>
                      <tbody id="usrlist">
                        <tr>
                          <td>John</td>
                          <td>Doe</td>
                          <td>john@example.com</td>
                          <td>July</td>
                        </tr>
                        <tr>
                          <td>Mary</td>
                          <td>Moe</td>
                          <td>mary@example.com</td>
                          <td>July</td>
                        </tr>
                        <tr>
                          <td>July</td>
                          <td>Dooley</td>
                          <td>july@example.com</td>
                          <td>July</td>
                        </tr>
                      </tbody>
                  </table>
              </div>
            </div>
            </div>
          </div>
        </div>
    <!-- about-model -->
        <div class="modal fade" id="modal-about" role="dialog">
          <div class="modal-dialog">
          
            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">About Coffee Project</h4>
              </div>
              <div class="modal-body">
                <p>This is a simple reservation (coffee) system.</p>
                <p>This web app is specially made for developers who share there coffeemachine with each other.
                So they can share the costs for producing coffee.</p>
                <p>Made By Kevin Lorenzo Storms</p>
                <p>Style is made by Jelle Romfield</p>
              </div>
            </div>
            
          </div>
        </div>
      <footer class="footer">
            <div class="container">
              <p class="text-muted">&copy; 2015 Kevin Lorenzo Storms</p>
            </div>
        </footer>
    </div>  
    <script type="text/javascript" src="./style/bower_components/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="./style/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="./js/coffeeMain.js"></script>
  <!-- Testing 
    <script type="text/javascript" src="../bower_components/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>-->
  </body>
</html>