<html>
	<head>
		<title>Coffee Time</title>
		      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="../materialize.min.css"  media="screen,projection"/>
       <link type="text/css" rel="stylesheet" href="../stle.css"  media="screen,projection"/>

      <script type="text/javascript" src="../bower_components/jquery/dist/jquery.min.js"></script>
      <script type="text/javascript" src="../../js/materialize.min.js"></script>

      <!--Let browser know website is optimized for mobile-->
     <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>

		<?php include './_funct/coffee.php'; ?>
		<link rel="stylesheet" type="text/css" href="./style/milkyStyle.css">
		<link rel="shortcut icon" href="./style/imgs/icon.ico">
		<style>
			
		</style>
	</head>
	<body>
	<?php 
	if(isset($_SESSION['user'])){
		if($_SESSION['user']['name'] != 'guest'){
			echo "<div class='goToManuBar'>
				<a href='?A=logout' class='customBTN'>Logout</a><br>
				<a href='./menu.php' class='customBTN' >Go to the menu</a> ".$_SESSION['user']."
			</div>";
		}
	}
			?>
		<div class="container">
			
				<div class="Jumbostron">
					<h1>BlackCoffee</h1>
				</div>
			
		<?php 	
		if(isset($_SESSION['user'])){
			if($_SESSION['user']['name'] == 'guest'){
				echo '
				<form method="post">
					<div class="form-group">
	   					<label for="exampleInputEmail1">usernme</label>
	    				<input type="text" class="form-control" title="usr" name="usr" placeholder="Username" required>
	  				</div>
	  				<div class="form-group">
	    				<label for="exampleInputPassword1">Password</label>
	   					<input type="password" class="form-control" title="passwd" name="passwd" placeholder="Password" required>
	 				 </div>
	  					
	  				<input class="btn" type="submit" title="login" name="login" value="login">
	  			</form>
			'
			;}
	     	}
			?>
			<div class="footer">
				<p>Copyright © <?php echo date('Y');?> KLST</p>
			</div>
		
		</div>
		<div class="info">
		<div class="infoButton col-md-4">
			<img width="195px" height="220px;" src="./style/imgs/poster.jpg">
					<a class="btn button-default cButton" href="#">About</a>
					
			</div>

		</div>	
		<script type="text/javascript" src="./style/bower_components/jquery/dist/jquery.min.js"></script>
		<script type="text/javascript" src="./style/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
	</body>
</html>